### ISSUE TITLE
Using Arduino Port Expander along with another custom esphome component

### ISSUE THREAD

**Issue by davidusb-geek** [glmnet/esphome_devices#2]
Hi there, this is more a question than an issue. Your APE code has been really helpful to me to use along different Wemos d1 mini in my home automation system. I'm trying to get the APE to work along with a second custom component in order to integrate a matrix keypad to activate/desactivate my home alarm. 
I'm want to use this custom component: https://github.com/Syralist/esphomekeypad
The problem I'm facing is that the keypad needs 8 i/o pins (so I'm out of pins with the Wemos d1 mini). So the question is if you think that it would be possible to use this custom keypad component using the expanded pins with you APE code.
For example in the `esphomekeypad/keypad_textsensor.h` file of the custom keypad component would it be possible to use the outputs defined with the APE ? like this (from file esphomekeypad/keypad_textsensor.h):
```
    byte colPins[n_cols] = {out1, out2, out3, out4};
    byte rowPins[n_rows] = {out5, out6, out7, out8};
``` 
Using these custom outputs with APE code:
```
output:
- platform: custom
  type: binary
  lambda: |-
    return {ape_binary_output(ape, 4),
            ape_binary_output(ape, 5),
            ape_binary_output(ape, 6),
            ape_binary_output(ape, 7), 
            ape_binary_output(ape, 8),
            ape_binary_output(ape, 9),
            ape_binary_output(ape, 10),
            ape_binary_output(ape, 11)};
  outputs:
    - id: out1
    - id: out2
    - id: out3
    - id: out4
    - id: out5
    - id: out6
    - id: out7
    - id: out8
```

**Comment by glmnet** [comment]
Hey there that would not work it that way, that keypad library of yours access the pins directly, not thru ESPHome API so it wont work.

What you can do is install the library in the Arduino sketch and get it working there, you will have to transfer the key presses to the ESP somehow.

Something that might work will be translating those keys to inputs for the ape, so you will see each key as an input.

once you get the library working on the arduino, modify the ape sketch so instead of doing `digitalRead(pin)`, you do a 
 `myKeypad.getKey()`

**Comment by davidusb-geek** [comment]
> Hey there that would not work it that way, that keypad library of yours access the pins directly, not thru ESPHome API so it wont work.
> 
> What you can do is install the library in the Arduino sketch and get it working there, you will have to transfer the key presses to the ESP somehow.
> 
> Something that might work will be translating those keys to inputs for the ape, so you will see each key as an input.
> 
> once you get the library working on the arduino, modify the ape sketch so instead of doing `digitalRead(pin)`, you do a
> `myKeypad.getKey()`

Ok, implementing the keypad library inside the APE code is not a problem, the thing is that the `myKeypad.getKey()` will return a `char`, so this cannot be a replace for `digitalRead(pin)`.
Do you think that it is possible to somehow send that `char` using i2c as a TextSensor? Any ideas on how achieve that?

**Comment by glmnet** [comment]
If it reads eg char value 5. Then You can replace the digital_read by the result of comparing the read with '5'

Something like ... 


bool button5_pressed = keypad.read() == '5';

**Comment by davidusb-geek** [comment]
Yes I see. I will give that a try. Thank you for your help :+1:

**Comment by NonaSuomy** [comment]
@davidusb-geek Did you actually figure this out? Would love to see if so.

**Comment by davidusb-geek** [comment]
No I tried to implement a solution for this and it never worked properly. I don't remember exactly why, there were some errors that I couldn't figure out. I finally got rid of the Wemos mini and used a separate arduino nano with more pins to deal with this.

**Comment by NonaSuomy** [comment]
:( Thanks for the reply was hoping you cracked it as I wanted to add a rotary encoder but had no idea where to start.

**Comment by davidusb-geek** [comment]
Yeah it was a bummer for me too. It could have been far more easy if the port expander supported this.
